### ISSUE TITLE
Unable to see methods

### ISSUE THREAD

**Issue by Tarnadas** [raendev/raen#21]
Hey,

I tried out Raen, but it seems like I'm unable to see methods. It seems like it's not working at all.
Deployed contract:
https://raen.dev/admin/#/dex-test.shrm.testnet
I tried out both your frontend and also nearblocks.io, which supports displaying contract methods, but no luck either.

Here is the contract file:
https://drive.proton.me/urls/9N1K8RN0Q0#3KigN0oIWnAF

Let me know, if you need any more information.

**Comment by willemneal** [comment]
Hmm strange. I'll take a look at your Wasm,but the source would be the most helpful.

**Comment by willemneal** [comment]
Can you also share the files in your `target/wit` folder?

**Comment by Tarnadas** [comment]
[orderly_dex.zip](https://github.com/raendev/raen/files/10660390/orderly_dex.zip)
Unfortunately they seem to look empty.
I can not yet share the source, but I really want this to be open sourced. It's the upcoming on-chain orderbook DEX from Orderly Network. I'll ask again regarding open sourcing.

One idea that might cause the issue, but haven't tested it:
My contract is in an extra lib folder. In its `Cargo.toml` I only enabled rlib crate type like this:
```toml
[lib]
crate-type = ["rlib"]
```
My actual contract has this lib as dependency:
```toml
[package]
name = "orderly-dex"
...

[lib]
crate-type = ["cdylib"]

[dependencies]
orderly-dex-lib = { path = "../contract-lib" }
```
and has cdylib enabled for wasm compilation. I do this to reduce code size from the wasm file, since enabling rlib makes the file quite a lot larger.

**Comment by willemneal** [comment]
Ah I see! I need to update the readme and documentation, but currently you need to add the following to the `Cargo.toml` any dependency that your contract uses that exposes an external interface, e.g `../contract-lib/Cargo.toml`:

```toml
[package.metadata.witgen]
export = true
```
